name: infinite_image
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio:
  http:
  get:
  intl:
  infinite_scroll_pagination:
  cached_network_image:
  path_provider:
  permission_handler:
  share_plus:
  image_downloader:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
